# Generated by Django 3.2.8 on 2021-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211027_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='end',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='extract',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='title',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
