# Generated by Django 3.2.8 on 2021-10-27 15:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20211027_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.CharField(default='I am a description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='extract',
            field=models.CharField(default='i am an extract', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
